### ISSUE TITLE
configure which coverage metric to be shown in chart

### ISSUE THREAD

**Issue by ronapelbaum** [jenkinsci/jacoco-plugin#39]
It would be really nice if i could'e configure which coverage metric was shown in the chart, i.e. I'm interested only in line coverage percentage, so I want to see only that in the chart.

**Comment by csimons** [comment]
This issue ticket has been migrated to JIRA ticket JENKINS-32721:

https://issues.jenkins-ci.org/browse/JENKINS-32721

Please watch this new ticket to be notified of further updates on this issue.
