### ISSUE TITLE
Support for coverage.xml generated by Android tools

### ISSUE THREAD

**Issue by itavero** [jenkinsci/jacoco-plugin#49]
When running `gradle createDebugCoverageReport` on an Android Gradle project, the built-in JaCoCo support builds an HTML report and an XML report.
As far as I know it is not possible to use this with Jenkins CI at the moment, because the plug-in wants the `.exec` file.

The report XML file starts with the following lines (looks like a standard format?):
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.0//EN" "report.dtd">
<report name="debug">
	<sessioninfo id="unknownhost-a0d58b54" start="1415952183361" dump="1415952207146"/>
```

I would love to see support for this in the Jenkins CI JaCoCo plug-in.

**Comment by bootstraponline** [comment]
Gradle already generates the report, it'd be nice if this plugin used it. :+1:

**Comment by bootstraponline** [comment]
I found using https://wiki.jenkins-ci.org/display/JENKINS/HTML%20Publisher%20Plugin is a decent work around. It doesn't have as many features however the report is exactly what gradle creates.

**Comment by itavero** [comment]
I do not think the HTML Publisher Plugin is a decent workaround, because it does not give me a trend and does not make it possible to fail a build if the coverage is too low.

**Comment by itavero** [comment]
Apparently I forgot to mention that I have also created an issue in the Jenkins issue tracker a while back.
See issue [#JENKINS-25616](https://issues.jenkins-ci.org/browse/JENKINS-25616) for more information.

**Comment by hunkim** [comment]
I also love to have this feature. Anyone working on it?

**Comment by centic9** [comment]
If we fix https://issues.jenkins-ci.org/browse/JENKINS-28652 it likely would provide a way to parse the XML report instead of the binary exec data.

**Comment by csimons** [comment]
This issue ticket has been migrated to JIRA ticket JENKINS-25616:

https://issues.jenkins-ci.org/browse/JENKINS-25616

Please watch this new ticket to be notified of further updates on this issue.
