### ISSUE TITLE
Ability to load properties from a file

### ISSUE THREAD

**Issue by Meems33** [jenkinsci/jacoco-plugin#52]
Currently the JaCoCo Jenkins plugin has 5 UI fields to set JaCoCo properties: exec files, class files, source files, inclusions. and exclusions. This causes an issue for us because it does not permit the use of dynamically generated inclusion/exclusion files and has overhead of maintaining job settings. It would be nice if there was an option to import properties from a file.

**Comment by csimons** [comment]
This issue ticket has been migrated to JIRA ticket JENKINS-32719:

https://issues.jenkins-ci.org/browse/JENKINS-32719

Please watch this new ticket to be notified of further updates on this issue.
