### ISSUE TITLE
Jacoco Code coverage issue

### ISSUE THREAD

**Issue by dparvath** [jenkinsci/jacoco-plugin#56]
Hello,
I am trying to show Integration testing in my sonar dash board and facing below issue.

When i am trying to generate the Jacoco report 

<jacoco:report>
		                           
		        <executiondata>
		            <file file="C:\jacoco\jacoco.exec"/>
		        </executiondata>
		                           
		        <structure name="Example Project">
		            <classfiles>
		                <fileset dir="C:\jacoco\classes" includes="**/*.class">		                
		                </fileset>
		            </classfiles>
		            <sourcefiles encoding="UTF-8">
		                <fileset dir="C:\jacoco\src" includes="**/*.java"/>
		            </sourcefiles>
		        </structure>
		                           
		        <html destdir="C:\jacoco\coveragereports"/>
		                           
	    	</jacoco:report>
		
Report is getting generated when i uses the class files that are in RAD/ECLIPSE build folder.When i am using the class files generated from jenkins report is not getting generated.

I am using same JDK for both classes.Can somebody please help.

**Comment by dparvath** [comment]
Getting below error displayed

[jacoco:report] Execution data for class com/****/caps/delegate/NewLoanDelegate does not match.
[jacoco:report] Execution data for class com/****/caps/delegate/ReportsDelegate does not match.
[jacoco:report] Execution data for class com/****/caps/control/form/LoanForm does not match.
[jacoco:report] Execution data for class com/****/caps/control/form/CriticalDocumentsForm does not match.
[jacoco:report] Execution data for class com/****/caps/control/form/BorrowerInformationForm does not match.
[jacoco:report] Execution data for class com/****/caps/control/form/LoanFundingForm does not match.
[jacoco:report] Execution data for class com/****/caps/control/form/PrimaryFundingForm does not match.
[jacoco:report] Execution data for class com/****/caps/control/helper/BorrowerInformationHelper does not 

Dont understand wats the difference between the class files generated by RAD in build folder and class files generated by ANT TASK

**Comment by centic9** [comment]
I think JaCoCo internally remembers which class files were used during generating the jacoco.exec file to prevent reporting invalid coverage as different class-files would often have different line-information, so it seems your build somehow has different binaries available at report-time than a runtime, which JaCoCo itself does not support. 

So I don't think we can do much on the side of the jacoco-plugin, please discuss with the jacoco team if you still see this issue.

**Comment by centic9** [comment]
One workaround/fix on your side might be to point the jacoco-plugin to the same binaries that are used while running the tests so that the same binaries are used here.
