### ISSUE TITLE
Adaptive Build Health Thresholds

### ISSUE THREAD

**Issue by martin1yness** [jenkinsci/jacoco-plugin#57]
This is a feature idea to support product teams adoption of test driven development (TDD). 

Right now it is a manual process to set the build failure thresholds, which is good in most cases. To support enforced improvement, these thresholds should be adaptive to the last successful build. That is, if the last successful build had a 81% test coverage, but the threshold was set to require only 80%, the threshold should automatically be increased.

This is a special mode and must be selected as an option. The threshold increase is intended to only allow test coverage improvement while disallowing degradation. The manual process of setting these thresholds is not scalable for organizations as the jobs grow exponentially.

**Comment by csimons** [comment]
This issue ticket has been migrated to JIRA ticket JENKINS-32718:

https://issues.jenkins-ci.org/browse/JENKINS-32718

Please watch this new ticket to be notified of further updates on this issue.
