### ISSUE TITLE
jacoco report data through api rest

### ISSUE THREAD

**Issue by GBeauny** [jenkinsci/jacoco-plugin#58]
Hi Guys, 

Is there any way to get data report from jacoco since jenkis api rest?
Is that implemented? 

Thanks,

**Comment by csimons** [comment]
Yes.  From the JaCoCo Coverage Report page, click the "REST API" link in the footer at the bottom of the page for documentation.  For instance, you can get access to all available coverage metrics in XML format by requesting the URL: http://hostname/job/job_name/build_number/jacoco/api/xml

Feel free to email jenkins-jacoco-plugin-mailing-list@googlegroups.com with any further questions about this plugin.
