### ISSUE TITLE
Multiple class directories and source directories not parsed if there is a space after comma delimiter

### ISSUE THREAD

**Issue by jurenovic** [jenkinsci/jacoco-plugin#59]
This does not work:

`app/build/intermediates/classes/staging/debug, data/build/intermediates/classes/debug`

when changing to this:

`app/build/intermediates/classes/staging/debug,data/build/intermediates/classes/debug`

 it works.

Relates to this line https://github.com/jenkinsci/jacoco-plugin/blob/master/src/main/java/hudson/plugins/jacoco/JacocoPublisher.java#L272

**Comment by csimons** [comment]
This issue ticket has been migrated to JIRA ticket JENKINS-32717:

https://issues.jenkins-ci.org/browse/JENKINS-32717

Please watch this new ticket to be notified of further updates on this issue.
