### ISSUE TITLE
JaCoCo 0.7.5 - Error / Warning should be printed out

### ISSUE THREAD

**Issue by vanniktech** [jenkinsci/jacoco-plugin#60]
Since JaCoCo 0.7.5 is not yet supported as discussed in #55 the plugin should in my opinion write something in the Console output of Jenkins saying that only JaCoCo up to version 0.7.4 is supported.

I have just been trying to figure out why the plugin did not work for the last 30 minutes.

**Comment by centic9** [comment]
This is closed in version 2.0.0 via #55 by upgrading to 0.7.5, older .exec files won't work any more as noone could provide code for handling both versions in parallel.
